/** @type {import('prettier').Config} */
module.exports = {
	endOfLine: 'lf',
	useTabs: true,
	singleQuote: true,
	jsxSingleQuote: true,
	semi: true,
	trailingComma: 'all',
	importOrder: [
		'^(react/(.*)$)|^(react$)',
		'^(next/(.*)$)|^(next$)',
		'<THIRD_PARTY_MODULES>',
		'',
		'^types$',
		'^@/env(.*)$',
		'^@/types/(.*)$',
		'^@/config/(.*)$',
		'^@/lib/(.*)$',
		'^@/hooks/(.*)$',
		'^@/components/ui/(.*)$',
		'^@/components/(.*)$',
		'^@/styles/(.*)$',
		'^@/app/(.*)$',
		'',
		'^[./]',
	],
	tailwindFunctions: ['clsx', 'cn'],
	importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
	plugins: [
		'@ianvs/prettier-plugin-sort-imports',
		'prettier-plugin-tailwindcss',
	],
};
