
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;

ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE "public"."Diner" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "receipt_id" bigint,
    "name" "text"
);

ALTER TABLE "public"."Diner" OWNER TO "postgres";

ALTER TABLE "public"."Diner" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Diner_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."Dish" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "receipt_id" bigint,
    "name" "text",
    "price" real
);

ALTER TABLE "public"."Dish" OWNER TO "postgres";

ALTER TABLE "public"."Dish" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Dish_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."Receipt" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "total" real,
    "tax" real,
    "tip" real,
    "subtotal" real,
    "receiptDate" timestamp with time zone,
    "paymentMethod" "text",
    "notes" "text",
    "user_id" "uuid"
);

ALTER TABLE "public"."Receipt" OWNER TO "postgres";

ALTER TABLE "public"."Receipt" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Receipt_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."diner_dish" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "diner_id" bigint,
    "dish_id" bigint
);

ALTER TABLE "public"."diner_dish" OWNER TO "postgres";

ALTER TABLE "public"."diner_dish" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."diner_dish_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."profiles" (
    "id" "uuid" NOT NULL,
    "updated_at" timestamp with time zone,
    "username" "text",
    "full_name" "text",
    "avatar_url" "text",
    "website" "text",
    CONSTRAINT "username_length" CHECK (("char_length"("username") >= 3))
);

ALTER TABLE "public"."profiles" OWNER TO "postgres";

ALTER TABLE ONLY "public"."Diner"
    ADD CONSTRAINT "Diner_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Dish"
    ADD CONSTRAINT "Dish_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Receipt"
    ADD CONSTRAINT "Receipt_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."diner_dish"
    ADD CONSTRAINT "diner_dish_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_username_key" UNIQUE ("username");

ALTER TABLE ONLY "public"."Diner"
    ADD CONSTRAINT "Diner_receipt_id_fkey" FOREIGN KEY ("receipt_id") REFERENCES "public"."Receipt"("id");

ALTER TABLE ONLY "public"."Dish"
    ADD CONSTRAINT "Dish_receipt_id_fkey" FOREIGN KEY ("receipt_id") REFERENCES "public"."Receipt"("id");

ALTER TABLE ONLY "public"."Receipt"
    ADD CONSTRAINT "Receipt_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."diner_dish"
    ADD CONSTRAINT "diner_dish_diner_id_fkey" FOREIGN KEY ("diner_id") REFERENCES "public"."Diner"("id");

ALTER TABLE ONLY "public"."diner_dish"
    ADD CONSTRAINT "diner_dish_dish_id_fkey" FOREIGN KEY ("dish_id") REFERENCES "public"."Dish"("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE "public"."Diner" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Dish" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone." ON "public"."profiles" FOR SELECT USING (true);

ALTER TABLE "public"."Receipt" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert their own profile." ON "public"."profiles" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));

CREATE POLICY "Users can update own profile." ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "id"));

ALTER TABLE "public"."diner_dish" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";

GRANT ALL ON TABLE "public"."Diner" TO "anon";
GRANT ALL ON TABLE "public"."Diner" TO "authenticated";
GRANT ALL ON TABLE "public"."Diner" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Diner_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Diner_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Diner_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Dish" TO "anon";
GRANT ALL ON TABLE "public"."Dish" TO "authenticated";
GRANT ALL ON TABLE "public"."Dish" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Dish_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Dish_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Dish_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Receipt" TO "anon";
GRANT ALL ON TABLE "public"."Receipt" TO "authenticated";
GRANT ALL ON TABLE "public"."Receipt" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Receipt_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Receipt_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Receipt_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."diner_dish" TO "anon";
GRANT ALL ON TABLE "public"."diner_dish" TO "authenticated";
GRANT ALL ON TABLE "public"."diner_dish" TO "service_role";

GRANT ALL ON SEQUENCE "public"."diner_dish_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."diner_dish_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."diner_dish_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
